// CHANGEMENT LANGUE

function changeLanguage(lang) {
    if (lang === 'fr') {
        document.getElementById('intro1').textContent = "L'industrie du manga a connu une croissance significative au fil des ans, avec la publication de nouveaux titres et l'expansion du lectorat à l'échelle mondiale. En tant que passionné d'analyse de données et de mangas, j'ai voulu explorer la façon dont les données peuvent révéler des informations clés sur cette industrie";
        document.getElementById('intro2').textContent = "L'industrie du manga a connu une croissance significative au fil des ans, avec de nouveaux titres qui captivent le public dans le monde entier. Cependant, un grand nombre des mangas les plus connus et les plus anciens arrivent à leur terme, comme One Piece et Attack on Titan.";
        document.getElementById('intro3').textContent = "L'objectif est d'identifier les futurs leaders potentiels du secteur sur la base de modèles historiques et de données actuelles.";
        document.getElementById('obj1').textContent = "L'objectif premier de ce projet était d'utiliser des données pour découvrir des tendances et des informations susceptibles d'aider à prédire quels mangas pourraient devenir les prochaines grandes histoires à succès.";
        document.getElementById('obj2').textContent = "Plus précisément, j'ai cherché à comprendre comment les classements des mangas ont évolué dans le temps, à identifier les genres les plus populaires et à analyser la corrélation entre les différentes catégories pour trouver des modèles dans le contenu des mangas.";
        document.getElementById('source1').textContent = "Les données utilisées pour ce projet proviennent de Kaggle, une plateforme bien connue pour les ensembles de données et les concours de science des données.";
        document.getElementById('source2').textContent = "L'ensemble de données comprend 70 939 mangas, leurs synopsis, chacun accompagné d'une note sur une échelle de 5 points, l'année de sortie, et les catégories associées. L'ensemble des données fournit une vue d'ensemble des aspects quantitatifs (notes et années de publication) et des caractéristiques qualitatives (catégories).";
        document.getElementById('prep1').textContent = "De nombreux mangas manquaient d'informations clés telles que leur date de sortie ou leur classement. J'ai donc commencé par nettoyer les données, en supprimant les mangas qui n'avaient pas de classement ou de catégorie. Pour les mangas restants sans année de sortie, si l'information n'était pas facilement accessible, je l'ai également supprimée. Le nombre de mangas étant faible, j'ai ajouté manuellement les années manquantes. J'ai également supprimé tous les doublons qui existaient dans l'ensemble de données. En conséquence, l'ensemble de données a été réduit de 70 393 mangas à 27 028.";
        document.getElementById('prep2').textContent = "Les catégories presque identiques ont été regroupées en une seule catégorie (par exemple, BL = Yaoi) .";
        document.getElementById('left').textContent = "J'ai commencé mon analyse en créant une nouvelle colonne pour classer les mangas dans des tranches d'années spécifiques (par exemple 2011-2020 ou Avant 2000) à l'aide de la formule IF d'Excel. ";
        document.getElementById('right1').textContent = "Pour déterminer le nombre de mangas pour chaque année, j'ai utilisé la formule COUNTA. ";
        document.getElementById('right2').textContent = "En outre, j'ai utilisé les formules MAX et MIN pour identifier les années de publication les plus anciennes et les plus récentes dans l'ensemble de données.";
        document.getElementById('pivot1').textContent = "J'ai créé des tableaux croisés dynamiques pour analyser les données de plusieurs manières. J'ai comparé les notes moyennes de chaque année, ce qui m'a permis de déterminer la note moyenne globale.";
        document.getElementById('pivot2').textContent = "J'ai également analysé les notes moyennes par catégorie, ainsi que les notes moyennes par tranches d'années spécifiques.";
        document.getElementById('pivot3').textContent = "En outre, j'ai créé un tableau croisé dynamique pour montrer le nombre de mangas par année. Pour améliorer l'interactivité, j'ai créé des graphiques liés à un segment, ce qui a permis aux utilisateurs de contrôler la fourchette d'années dans toutes les visualisations simultanément..";
        document.getElementById('cat1').textContent = "Comme les catégories de mangas étaient à l'origine listées dans une seule cellule pour chaque manga, j'ai utilisé Power Query pour transformer ces données catégorielles en lignes individuelles, en veillant à ce que chaque catégorie soit représentée séparément.";
        document.getElementById('cat2').textContent = "Cette transformation m'a permis de générer des tableaux croisés dynamiques supplémentaires analysant la relation entre les catégories et le nombre de mangas, ainsi que les catégories et leurs évaluations respectives.";
        document.getElementById('corr').textContent = "J'ai construit une matrice de corrélation pour comprendre les relations entre les catégories et les évaluations. J'ai échantillonné 1086 mangas et ajouté des colonnes binaires pour les 14 catégories les plus importantes. À l'aide de la fonction CORREL, j'ai calculé les coefficients de corrélation et appliqué une mise en forme conditionnelle pour représenter visuellement ces corrélations, ce qui facilite l'interprétation de la force et de la direction des relations entre les catégories.";
        document.getElementById('seg').textContent = "Le tableau de bord comporte des segments qui permettent aux utilisateurs de se concentrer sur des tranches d'années ou des catégories spécifiques. Cette fonctionnalité permet aux utilisateurs d'isoler des périodes ou des genres particuliers, facilitant ainsi une analyse plus détaillée des tendances et des modèles.";
        document.getElementById('chart1').textContent = "Les cotes moyennes des mangas sont assez instables avant 1980. Cependant, de 1980 à 2022, on observe une nette tendance à la hausse. La ligne de tendance suggère que cette augmentation pourrait se poursuivre à l'avenir.";
        document.getElementById('chart2').textContent = "Dans l'ensemble de données, la majorité des mangas sont concentrés dans les années 2011-2020 et 2000-2010. En outre, l'année de sortie moyenne des mangas dans ces tranches est 2006 et 2016, respectivement.";
        document.getElementById('chart3').textContent = " Les catégories les plus fréquemment utilisées, qui contiennent également les mangas les mieux notés (avec des notes moyennes comprises entre 4,6 et 4,7), comprennent la romance, le yaoi - où la moitié des mangas sont classés -, le drame, la comédie, l'école, la fantaisie, la couleur, les webtoons, l'action et le manhwa. Ces dernières catégories représentent environ un quart de l'ensemble des données. Il convient de noter que très peu de mangas ont une note supérieure à 4,6 sur 5.";
        document.getElementById('chart4').textContent = "Le tableau de corrélation révèle que certaines catégories apparaissent fréquemment ensemble et présentent de fortes corrélations, telles que Webtoons et Full Color, avec un coefficient de corrélation de 0,897. En revanche, certaines combinaisons, comme Romance et Action, présentent une très faible corrélation, avec un coefficient de -0,298. La plupart des catégories ont toutefois tendance à être relativement indépendantes les unes des autres.";
        document.getElementById('interp1').textContent = "L'instabilité des cotes moyennes des mangas avant 1980 reflète probablement le nombre plus restreint de mangas publiés au cours de cette période, ce qui rend difficile l'établissement de conclusions cohérentes. La tendance à la hausse des cotes à partir de 1980 suggère soit une amélioration de la qualité des mangas au fil du temps, soit des changements dans les préférences du public qui se sont traduits par des cotes plus élevées. La ligne de tendance suggère en outre que, si ces tendances se poursuivent, on peut s'attendre à ce que les cotes moyennes continuent d'augmenter à l'avenir.";
        document.getElementById('interp2').textContent = "La concentration des sorties de mangas entre 2000 et 2020 indique une période de croissance rapide de l'industrie, probablement due à la popularité mondiale des mangas et à l'essor des plateformes numériques. Les années de sortie moyennes de 2006 et 2016 mettent en évidence des périodes clés de la production de mangas, correspondant à des développements significatifs dans l'édition et la distribution.";
        document.getElementById('interp3').textContent = "Les catégories telles que Romance, Yaoi, Drama et autres ne dominent pas seulement l'ensemble des données en termes de nombre de mangas, mais ont également tendance à avoir des classements plus élevés. Cela suggère que ces genres peuvent être plus attrayants pour le public ou attirer des œuvres de meilleure qualité. À l'inverse, la rareté des mangas dont la note est supérieure à 4,6 indique qu'il est difficile d'obtenir des notes exceptionnelles, ce qui peut refléter des normes de lecture plus strictes ou la difficulté de produire des œuvres universellement acclamées.";
        document.getElementById('interp4').textContent = "Les fortes corrélations, en particulier entre Webtoons et Full Color, Full Color et Manhwa, Manhwa et Webtoons, ainsi que Fantasy et Adventure, suggèrent que ces catégories se retrouvent fréquemment dans l'ensemble de données. Cela reflète probablement le style et le format spécifiques associés à ces catégories. Par exemple, de nombreux webtoons sont en couleur et proviennent de Corée du Sud (Manhwa), tandis que la fantasy et l'aventure sont des genres qui partagent souvent des éléments narratifs similaires, ce qui rend leur association fréquente peu surprenante. L'indépendance générale de la plupart des autres catégories indique que les genres de manga ont tendance à être autonomes et à répondre aux préférences de publics distincts.";
        document.getElementById('sum1').textContent = "En résumé, l'analyse des données sur les mangas révèle plusieurs tendances clés. Tout d'abord, l'instabilité des taux d'audience avant 1980 contraste fortement avec l'augmentation constante des taux d'audience à partir de 1980, ce qui suggère un changement dans la qualité des mangas ou dans les préférences du public. La concentration des sorties de mangas entre 2000 et 2020 met en évidence un boom de l'industrie, dû en partie aux plateformes numériques. Les catégories populaires comme la romance, le yaoi, le drame et la comédie dominent non seulement en nombre, mais ont également tendance à avoir des taux d'audience plus élevés, ce qui indique un fort attrait pour le public. Toutefois, très peu de mangas dépassent la note de 4,6, ce qui montre qu'il est difficile d'obtenir des notes exceptionnelles.";
        document.getElementById('sum2').textContent = "L'analyse des corrélations révèle des liens étroits entre certaines catégories, en particulier les webtoons, la couleur, le manhwa, la fantaisie et l'aventure, qui apparaissent fréquemment ensemble. Cela suggère que certains formats et genres se complètent naturellement, ce qui favorise l'engagement des lecteurs " ;
        document.getElementById('recomm').textContent = "Sur la base de ces résultats, des analyses futures pourraient explorer l'influence d'auteurs, d'éditeurs ou de studios individuels sur le succès des mangas. En outre, l'étude du rôle de la distribution numérique et du lectorat international pourrait fournir des informations plus approfondies sur l'expansion mondiale de l'industrie. Enfin, l'analyse des sentiments sur les critiques des utilisateurs pourrait fournir des explications plus nuancées sur les évaluations, en aidant à identifier les facteurs spécifiques qui augmentent la satisfaction des lecteurs.";
        document.getElementById('learn1').textContent = "Ce projet m'a permis d'approfondir ma compréhension de l'analyse des données et de son application pratique dans l'exploration des tendances au sein d'une industrie spécifique comme celle des mangas. J'ai amélioré mes compétences en matière de nettoyage et de transformation des données, notamment en utilisant Power Query pour traiter des données catégorielles complexes.";
        document.getElementById('learn2').textContent = "Grâce à ce projet, j'ai également amélioré ma capacité à visualiser les données de manière efficace, en rendant les informations plus accessibles et compréhensibles grâce à des graphiques et des tableaux clairs. J'ai appris à créer et à utiliser des segments pour me concentrer sur des années ou des catégories spécifiques, ce qui a grandement amélioré mes capacités d'analyse. Comprendre comment appliquer ces segments m'a permis de disséquer les données plus efficacement, en fournissant des informations plus claires sur les tendances et les modèles dans des sous-ensembles ciblés de données.";
        document.getElementById('prom').textContent = "Quels sont les facteurs qui influencent le succès d'un manga ?";
        document.getElementById('objh').textContent = "Objectif";
        document.getElementById('dataprep').textContent = "Préparation des données";
        document.getElementById('dataset').textContent = "La base de donnée";
        document.getElementById('chartkey').textContent = "Les graphiques et points clés";
        document.getElementById('int').textContent = "Interprétations";
        document.getElementById('summa').textContent = "Résumé des découvertes";
        document.getElementById('re').textContent = "Recommendation";
        document.getElementById('bellinna').textContent = "Apprentissage";
    } else if (lang === 'en') {
        document.getElementById('intro1').textContent = "The manga industry has experienced significant growth over the years, with new titles being published and readership expanding globally. As someone passionate about both data analysis and manga, I wanted to explore how data can reveal key insights about this industry.";
        document.getElementById('intro2').textContent = "The manga industry has seen significant growth over the years, with new titles captivating audiences worldwide. However, many of the most well-known and long-running mangas are reaching their conclusions, such as One Piece and Attack on Titan.";
        document.getElementById('intro3').textContent = "The goal is to identify potential future leaders in the industry based on historical patterns and current data."
        document.getElementById('obj1').textContent = "The primary objective of this project was to use data to uncover trends and insights that could help predict which mangas might become the next big success stories.";
        document.getElementById('obj2').textContent = "Specifically, I focused on understanding how manga ratings have changed over time, identifying the most popular genres, and analyzing the correlation between different categories to find patterns in manga content.";
        document.getElementById('source1').textContent = "The data used for this project was sourced from Kaggle, a well-known platform for datasets and data science competitions.";
        document.getElementById('source2').textContent = "The dataset consists of 70 939 manga, their synospis, each accompanied by a rating on a 5-point scale, the year of release, and associated categories. The dataset provides a comprehensive view of both quantitative aspects (ratings and release years) and qualitative characteristics (categories).";
        document.getElementById('prep1').textContent = "There were many mangas missing key information such as their release date or rating. So, I began by cleaning the data, removing mangas that had no ratings or categories. For the remaining mangas without a release year, if the information was not easily accessible, I removed them as well. Since the number was small, I manually added the missing years. I also removed any duplicates that existed in the dataset. As a result, the dataset was reduced from 70,393 mangas to 27,028.";
        document.getElementById('prep2').textContent = "Categories that are almost identical were grouped into a single category (e.g., BL = Yaoi).";
        document.getElementById('left').textContent = "I began my analysis by creating a new column to categorize mangas into specific year ranges (e.g 2011-2020 or Before 2000) using the IF formula in Excel. ";
        document.getElementById('right1').textContent = "To determine the number of mangas within each year range, I utilized the COUNTA formula. ";
        document.getElementById('right2').textContent = "Additionally, I employed the MAX and MIN formulas to identify the oldest and most recent publication years in the dataset.";
        document.getElementById('pivot1').textContent = "I created pivot tables to analyze the data in several ways. I compared average ratings across each year, which allowed me to determine the overall average rating.";
        document.getElementById('pivot2').textContent = "I also analyzed average ratings by category, as well as average ratings within specific year ranges.";
        document.getElementById('pivot3').textContent = "Additionally, I created a pivot table to show the number of mangas per year range. To enhance interactivity, I set up charts linked to a segment, which enabled users to control the year range across all visualizations simultaneously.";
        document.getElementById('cat1').textContent = "Since manga categories were originally listed in a single cell for each manga, I used Power Query to transform this categorical data into individual rows, ensuring that each category was represented separately";
        document.getElementById('cat2').textContent = "This transformation allowed me to generate additional pivot tables analyzing the relationship between categories and manga counts, as well as categories and their respective ratings.";
        document.getElementById('corr').textContent = "I constructed a correlation matrix to understand the relationships between categories and ratings. I sampled 1086 mangas and added binary columns for the top 14 categories. Using the CORREL function, I calculated the correlation coefficients and applied conditional formatting to visually represent these correlations, making it easier to interpret the strength and direction of the relationships between categories.";
        document.getElementById('seg').textContent = "The dashboard features segments that allow users to focus on specific year ranges or categories. This functionality enables users to isolate particular time periods or genres, facilitating a more detailed analysis of trends and patterns";
        document.getElementById('chart1').textContent = "The average manga ratings are quite unstable before 1980. However, from 1980 until 2022, we see a clear upward trend. The trendline suggests that this increase could continue in the future.";
        document.getElementById('chart2').textContent = "In the dataset, the majority of manga are concentrated in the year ranges between 2011-2020 and 2000-2010. Additionally, the average release year for manga in these ranges is 2006 and 2016, respectively.";
        document.getElementById('chart3').textContent = "The most frequently used categories, which also have the highest-rated manga (with average ratings between 4.6 and 4.7), include Romance, Yaoi—where half of the manga are categorized—Drama, Comedy, School, Fantasy, Full Color, Webtoons, Action, and Manhwa. The latter categories represent about a quarter of the dataset. It is worth noting that very few manga have ratings above 4.6 out of 5.";
        document.getElementById('chart4').textContent = "The correlation table reveals certain categories that appear frequently together and have strong correlations, such as Webtoons and Full Color, with a correlation coefficient of 0.897. On the other hand, some combinations, like Romance and Action, show very low correlation, with a coefficient of -0.298. Most categories, however, tend to be relatively independent of one another.";
        document.getElementById('interp1').textContent = "The instability of average manga ratings before 1980 likely reflects the smaller number of mangas released during that period, making it difficult to draw consistent conclusions. The upward trend in ratings from 1980 onwards suggests either an improvement in manga quality over time or changes in audience preferences that have resulted in higher ratings. The trendline further suggests that, if these patterns continue, we could expect average ratings to keep rising in the future.";
        document.getElementById('interp2').textContent = "The concentration of manga releases in the 2000-2020 range indicates a period of rapid growth in the industry, possibly due to the global popularity of manga and the rise of digital platforms. The average release years of 2006 and 2016 highlight key periods of manga production, aligning with significant developments in publishing and distribution.";
        document.getElementById('interp3').textContent = "Categories such as Romance, Yaoi, Drama, and others not only dominate the dataset in terms of the number of mangas but also show a tendency to have higher ratings. This suggests that these genres may appeal more to the audience or attract better-quality works. Conversely, the rarity of mangas with ratings above 4.6 indicates that exceptional ratings are hard to achieve, which may reflect stricter reader standards or the challenges of producing universally acclaimed works.";
        document.getElementById('interp4').textContent = "The strong correlations, particularly between Webtoons and Full Color, Full Color and Manhwa, Manhwa and Webtoons, as well as Fantasy and Adventure, suggest that these categories frequently co-occur in the dataset. This likely reflects the specific style and format associated with these categories. For instance, many Webtoons are both in full color and originate from South Korea (Manhwa), while Fantasy and Adventure are genres that often share similar narrative elements, making their frequent pairing unsurprising. The general independence of most other categories indicates that manga genres tend to stand alone, catering to distinct audience preferences.";
        document.getElementById('sum1').textContent = "In summary, the analysis of manga data reveals several key trends. First, the instability in ratings prior to 1980 contrasts sharply with the steady increase in ratings from 1980 onward, suggesting a shift in either manga quality or audience preferences. The concentration of manga releases between 2000 and 2020 highlights a boom in the industry, driven in part by digital platforms. Popular categories like Romance, Yaoi, Drama, and Comedy not only dominate in numbers but also tend to have higher ratings, indicating a strong audience appeal. However, very few mangas surpass a rating of 4.6, reflecting the challenge of achieving exceptional ratings.";
        document.getElementById('sum2').textContent = "The correlation analysis reveals strong connections between certain categories, especially Webtoons, Full Color, Manhwa, Fantasy, and Adventure, which frequently appear together. This suggests that certain formats and genres naturally complement each other, driving higher reader engagement.";
        document.getElementById('recomm').textContent = "Based on these findings, future analysis could explore the influence of individual authors, publishers, or studios on manga success. Additionally, investigating the role of digital distribution and international readership could provide deeper insights into the global expansion of the industry. Lastly, conducting sentiment analysis on user reviews might offer more nuanced explanations behind the ratings, helping to identify specific factors that drive higher reader satisfaction.";
        document.getElementById('learn1').textContent = "This project has deepened my understanding of data analysis and its practical application in exploring trends within a specific industry like manga. I have enhanced my skills in data cleaning and transformation, particularly using Power Query to handle complex categorical data.";
        document.getElementById('learn2').textContent = "Through this project, I have also improved my ability to visualize data effectively, making insights more accessible and understandable through clear charts and tables. I learned how to set up and utilize segments to focus on specific years or categories, which greatly enhanced my analytical capabilities. Understanding how to apply these segments allowed me to dissect data more effectively, providing clearer insights into trends and patterns within targeted subsets of the data.";
        document.getElementById('prom').textContent = "What factors influence the success of a manga?";
        document.getElementById('objh').textContent = "Objective";
        document.getElementById('dataprep').textContent = "Data preparation";
        document.getElementById('dataset').textContent = "The dataset";
        document.getElementById('chartkey').textContent = "Charts and Key Insights";
        document.getElementById('int').textContent = "Interpretation";
        document.getElementById('summa').textContent = "Summary of discoveries";
        document.getElementById('re').textContent = "Recommendation";
        document.getElementById('bellinna').textContent = "Personal Learnings";

    }
}