// CHANGEMENT LANGUE

function changeLanguage(lang) {
    if (lang === 'fr') {
        //INTRO
        document.getElementById('intro1').textContent = "Le paysage marketing évolue rapidement, les entreprises se disputant l'attention des consommateurs dans un marché de plus en plus saturé.";
        document.getElementById('intro2').textContent = "Les méthodes traditionnelles de planification des campagnes ne suffisent plus ; les spécialistes du marketing doivent prendre des décisions éclairées, fondées sur des informations concrètes concernant le comportement, les préférences et les tendances des consommateurs.";
        document.getElementById('intro3').textContent = "Dans ce contexte, la capacité à analyser les données historiques et à prédire les résultats futurs est devenue un avantage concurrentiel vital. En tirant parti de l'analyse des données, les entreprises peuvent mieux répartir leurs ressources, personnaliser leurs messages et optimiser le calendrier et les canaux de leurs campagnes.";
        //OBJECTIVE
        document.getElementById('problematic').textContent = "Comment pouvons-nous optimiser les futures campagnes de marketing pour maximiser l'engagement des clients grâce à la modélisation prédictive ?";
        document.getElementById('obj-h2').textContent = "Objectif";
        document.getElementById('obj1').textContent = "L'objectif était d'exploiter les données historiques de la société XYZ, notamment les profils des clients, les résultats des campagnes et les performances des canaux de distribution, afin d'élaborer un modèle permettant de prévoir le succès des campagnes futures. Ce modèle vise à fournir des informations exploitables pour affiner les stratégies de marketing et améliorer l'efficacité globale des campagnes.";
        //SOURCE
        document.getElementById('dataset-h2').textContent = "La base de données";
        document.getElementById('source1').textContent = "Les données utilisées pour ce projet proviennent de Kaggle, une plateforme bien connue pour les ensembles de données et les concours de science des données.";
        document.getElementById('source2').textContent = "L'ensemble de données comprend 2 205 observations et 39 variables quantitatives. Parmi ces variables figurent des paramètres clés tels que l'âge, le revenu, le fait que la personne ait répondu positivement à la campagne N et le montant dépensé pour certains achats.";
        //SOME INFO
        document.getElementById('someinfo-h2').textContent = "Quelques informations clés";
        document.getElementById('info').textContent = "Les revenus des participants varient de 1 730 € à 113 734 € par an. Au moins la moitié des participants n'ont pas d'enfants à charge. L'âge des clients varie de 24 à 80 ans, avec une moyenne d'environ 51 ans.";
        //PREPARATION
        document.getElementById('dataprep-h2').textContent = "Préparation des données pour un nouveau modèle";
        document.getElementById('prep1').textContent = "Dans notre phase de préparation des données, nous construisons un modèle en utilisant le nombre total d'acceptations de la campagne comme variable de réponse. Pour améliorer la précision et la pertinence de notre modèle de régression linéaire, nous utilisons la fonction regsubsets. Cette fonction permet de sélectionner les variables les plus pertinentes en évaluant tous les sous-ensembles possibles de prédicteurs.";
        document.getElementById('prep2').textContent = "En nous concentrant sur les variables les plus significatives, nous affinons notre modèle pour mieux prédire la probabilité de réussite de la campagne, ce qui garantit une analyse plus solide et plus perspicace.";
        document.getElementById('problem1').textContent = "Le modèle que nous avons créé présente des dépendances linéaires entre certaines variables. Le problème se pose lorsque plusieurs variables prédictives sont fortement corrélées, ce qui rend difficile pour l'algorithme de régression de distinguer leur impact individuel sur la variable cible.";
        // CORRELATION
        document.getElementById('corr1').textContent = "Cette multicolinéarité peut conduire à des estimations instables des coefficients, ce qui réduit l'interprétabilité du modèle. Par conséquent, nous vérifierons les corrélations afin d'identifier et de traiter toute variable fortement corrélée avant de procéder à l'ajustement du modèle.";
        document.getElementById('corr2').textContent = "L'examen de la matrice de corrélation fournie montre que plusieurs paires de variables présentent de fortes corrélations (en valeur absolue). Notamment, la corrélation entre le revenu et le MntTotal est de 0,823, ce qui indique une relation substantielle entre le revenu d'un client et ses dépenses totales. De même, MntWines et MntTotal sont fortement corrélés (corr = 0,9617), de même que MntMeatProducts et MntTotal (corr = 0,9435). D'autres paires notables sont MntFruits et MntTotal (corr = 0,9288), MntProduits sucrés et MntTotal (corr = 0,9079), et MntProduits de la pêche et MntTotal (corr = 0,8875). Ces fortes corrélations suggèrent que les dépenses totales sont fortement influencées par les dépenses effectuées dans les différentes catégories de produits.";
        document.getElementById('resolcorr1').textContent = "Pour éviter les erreurs de modèle, nous omettons les variables suivantes : MntVins, MntProduits de viande, MntFruits, MntProduits sucrés, MntProduits de poisson, MntProduits ordinaires, AcceptedCmp1, AcceptedCmp2, AcceptedCmp3, AcceptedCmp4, et AcceptedCmp5.";
        document.getElementById('resolcorr2').textContent = "En outre, certaines variables telles que Z_CostContact et Z_Revenue ne semblent pas contribuer à la variance d'autres variables. En outre, nous ne disposons pas d'informations suffisantes sur leur nature et leur pertinence, ce qui suggère qu'elles pourraient être supprimées de l'ensemble de données.";
        document.getElementById('resolcorr3').textContent = "Ces variables peuvent introduire une multicolinéarité ou ajouter du bruit au modèle sans fournir de pouvoir prédictif significatif. En les excluant, nous visons à améliorer la précision et l'interprétabilité du modèle.";
        //NEW MODEL
        document.getElementById('newmodel-h2').textContent = "Un modèle linéaire ridge";
        document.getElementById('newmodel1').textContent = "J'utilise la fonction glmnet pour ajuster les modèles de régression, ce qui permet de régulariser les coefficients afin de mieux gérer des problèmes tels que la multicolinéarité. Cette méthode réduit l'impact des variables fortement corrélées tout en conservant toutes les variables dans le modèle, car certaines des variables restantes présentent encore de fortes corrélations.";
        document.getElementById('newmodel2').textContent = "Nous procédons à l'ajustement du modèle de Ridge à l'aide de glmnet, et ce nouveau modèle sera appelé « best_model ». L'étape suivante consiste à afficher les coefficients de chaque variable, ce qui est crucial pour interpréter le modèle et comprendre l'importance relative de chaque variable explicative.";
        document.getElementById('newmodel3').textContent = "Dans notre cas, pour une régression linéaire, chaque coefficient indiquera de combien la variable cible change en moyenne pour une variation d'une unité de la variable explicative, en maintenant tous les autres facteurs constants. Cela signifie que chaque coefficient représente l'effet isolé de la variable correspondante sur la cible, ce qui permet de mieux comprendre la relation entre les prédicteurs et le résultat recherché.";
        document.getElementById('newmodel4').textContent = "Dans le modèle, les variables ayant des coefficients non nuls sont considérées comme ayant un impact sur la variable cible. Un coefficient positif indique qu'une augmentation de la variable explicative entraîne une augmentation de la variable cible. Inversement, un coefficient négatif implique qu'une augmentation de la variable explicative entraîne une diminution de la variable cible. Les variables ayant des coefficients nuls peuvent être ignorées dans l'interprétation, car elles n'ont pas d'influence significative sur le résultat.";
        document.getElementById('newmodel5').textContent = "Nous avons créé un modèle linéaire (à l'aide de la fonction lm) et généré un résumé des résultats. La valeur R² est de 0,431, ce qui indique que le modèle explique environ 43,1 % de la variance totale de la variable dépendante. Cela suggère que le modèle capture une part significative de la variabilité observée. Le test F évalue la signification globale du modèle.";
        document.getElementById('newmodel6').textContent = "Avec une statistique F de 66,01 et une valeur p proche de zéro (valeur p : 2,2e-16), cela implique que le modèle dans son ensemble est statistiquement significatif. En d'autres termes, au moins une des variables indépendantes a un effet significatif sur la variable dépendante. L'analyse révèle également des tendances notables : pour chaque adolescent supplémentaire dans le ménage, la probabilité d'accepter la campagne de marketing diminue de 0,059. ";
        document.getElementById('newmodel7').textContent = "Dans notre modèle, nous avons constaté que chaque achat promotionnel est lié à une diminution de 0,0366 du taux d'acceptation, tandis que chaque achat en magasin entraîne une réduction de 0,02528. Inversement, les clients qui ont accepté la campagne la plus récente affichent une augmentation significative de 0,6566 de la variable dépendante. En ce qui concerne l'éducation, des niveaux tels que le second cycle, le niveau de base et le diplôme sont associés à des taux de réponse plus élevés, ce qui souligne l'influence significative de l'éducation sur les attitudes liées à la variable dépendante."
        //TEST
        document.getElementById('test-h2').textContent = "Test statistique sur les données";
        document.getElementById('test1').textContent = "Nous allons effectuer des tests de normalité (Shapiro-Wilk), d'hétéroscédasticité (Breusch-Pagan) et d'autocorrélation des résidus (Durbin-Watson), avec un seuil de signification de 0,05 pour chacun d'entre eux.";
        document.getElementById('test2').textContent = "Le test de Shapiro-Wilk vérifie si les résidus d'un modèle de régression suivent une distribution normale. La normalité des résidus est cruciale pour certains modèles de régression, notamment pour la validité des tests de signification (valeurs p) et des intervalles de confiance.";
        document.getElementById('test3').textContent = "L'hypothèse d'homoscédasticité (variance constante des erreurs) est une condition clé de la régression linéaire classique. Si cette hypothèse n'est pas respectée (c'est-à-dire en cas d'hétéroscédasticité), les erreurs standard des coefficients estimés peuvent être inexactes, ce qui affecte la fiabilité des valeurs p et des intervalles de confiance. Un modèle présentant une hétéroscédasticité peut produire des prédictions moins fiables et sous-estimer la variabilité des estimations.";
        document.getElementById('test4').textContent = " Le test de Durbin-Watson vérifie l'autocorrélation des résidus, c'est-à-dire si les erreurs (résidus) d'un modèle sont corrélées entre elles. Si les résidus sont corrélés, cela indique que le modèle n'a pas capturé toute la structure des données. L'autocorrélation peut entraîner des estimations de coefficients inefficaces, ce qui a un impact sur le pouvoir prédictif du modèle.";
        document.getElementById('test5').textContent = "Pour un seuil de 5%, nous observons que ces trois tests sont réussis.";
        //CHART
        document.getElementById('chart-h2').textContent = "Graphiques et informations clés";
        document.getElementById('chart1').textContent = "Sans aucun doute, la grande majorité des clients n'a pas répondu positivement à l'une des campagnes publicitaires que nous avons menées. Nous devrions nous concentrer sur l'identification des critères clés liés aux comportements de nos clients. Ainsi, nous pourrons mieux allouer nos investissements marketing, en nous assurant qu'ils soient ciblés et plus susceptibles de produire des résultats positifs.";
        document.getElementById('chart2').textContent = "Nous pouvons observer que presque tous les clients font leurs achats en magasin, mais beaucoup n'utilisent pas le catalogue. Cela représente une opportunité d'amélioration, soit en révisant le contenu du catalogue, soit en augmentant sa distribution à un public plus large. De plus, le site web du magasin joue un rôle important dans la stimulation des achats. Nous pourrions envisager d'investir davantage dans le marketing numérique pour attirer plus de clients, surtout à l'ère numérique actuelle.";
        document.getElementById('chart3').innerHTML = "Nous pouvons observer que la grande majorité des clients achètent en magasin, bien que beaucoup n'utilisent pas le catalogue. Cela représente une opportunité d'amélioration, soit en révisant le contenu du catalogue, soit en le distribuant à un public plus large. <br> De plus, le site web du magasin joue un rôle important dans la stimulation des achats. Nous pourrions nous concentrer sur l'augmentation des efforts de marketing numérique pour attirer plus de clients, surtout à notre époque actuelle, qui devient de plus en plus numérique.";        
        //AGE CORRELATION
        document.getElementById('agecorr-h2').textContent = "Âge et corrélation";
        document.getElementById('agecorr').innerHTML = "Nous observons que la majorité des clients ont entre 30 et 70 ans, ce qui peut être identifié comme des adultes, des parents, voire des grands-parents. <br> Le graphique montre la corrélation entre l'âge des clients et le nombre de campagnes publicitaires acceptées (`AcceptedCmpOverall`). Chaque point représente un client, avec l'âge sur l'axe des abscisses et le nombre de campagnes acceptées sur l'axe des ordonnées. <br> Il semble que l'acceptation des campagnes ne soit pas fortement influencée par l'âge. Les valeurs d'acceptation sont réparties dans tous les groupes d'âge sans tendance claire. Cela suggère qu'il n'existe pas de relation évidente entre l'âge et la probabilité d'accepter les campagnes publicitaires, indiquant qu'une stratégie marketing basée uniquement sur l'âge ne serait pas optimale. Il serait préférable de concevoir des campagnes qui plaisent à un large public pour maximiser la portée.";
        //INTERPRETATION
        document.getElementById('interp-h2').textContent = "Interprétation";
        document.getElementById('interp1').textContent = "En conclusion, notre analyse révèle des informations importantes sur le comportement des clients et l'efficacité des campagnes de marketing. Bien que nous ayons initialement émis l'hypothèse que des facteurs tels que l'âge pouvaient jouer un rôle crucial dans l'acceptation de la campagne, les données montrent le contraire. L'analyse de corrélation ne suggère aucune relation claire entre l'âge et l'acceptation de la campagne, ce qui indique que le marketing ciblé en fonction de l'âge n'est peut-être pas efficace. ";
        document.getElementById('interp2').textContent = "Au contraire, nos résultats soulignent l'importance d'une approche marketing large et inclusive. La corrélation entre le revenu et les dépenses totales suggère que les clients ayant des revenus plus élevés ont tendance à dépenser davantage dans toutes les catégories, ce qui souligne la nécessité de proposer des offres ciblées basées sur le pouvoir d'achat plutôt que sur des caractéristiques démographiques telles que l'âge.";
        document.getElementById('interp3').textContent = "De plus, le processus de sélection des variables et le modèle de régression Ridge ont permis d'affiner le pouvoir prédictif en se concentrant sur les facteurs les plus significatifs, améliorant ainsi la robustesse et l'interprétabilité du modèle. Les tests statistiques indiquent que notre modèle répond aux hypothèses nécessaires pour une analyse fiable, ce qui donne confiance dans les résultats.";
        document.getElementById('interp4').textContent = "En termes de stratégies exploitables, l'amélioration de l'utilisation du catalogue et l'investissement dans les canaux de marketing numérique semblent être des domaines prometteurs. Le site web du magasin s'est avéré être un moteur d'achat important, ce qui suggère que l'amélioration de nos efforts de marketing numérique pourrait attirer plus de clients, en particulier dans le paysage numérique d'aujourd'hui." ;
        document.getElementById('interp5').textContent = "En fin de compte, notre objectif devrait être d'identifier les critères comportementaux clés qui peuvent guider l'investissement marketing, en veillant à ce que les campagnes soient à la fois efficaces et efficientes, en maximisant les taux de réponse et en améliorant le retour sur investissement.";
        //RECOMMENDATION
        document.getElementById('recom-h2').textContent = "Recommendation";
        document.getElementById('recomtext').textContent = "Tout d'abord, une analyse détaillée de la segmentation de la clientèle devrait être effectuée afin de concevoir des campagnes plus ciblées pour différents groupes. En outre, une analyse comportementale plus poussée pourrait permettre d'identifier les motivations qui sous-tendent les décisions d'achat, ce qui fournirait des critères de ciblage plus précis. Des tests A/B de différentes versions de campagnes nous permettraient de déterminer les approches les plus efficaces, tandis que l'intégration de sources de données supplémentaires, telles que l'engagement dans les médias sociaux ou les données géographiques, pourrait améliorer la précision des prédictions. L'analyse des commentaires des clients, tels que les avis ou les réponses aux enquêtes, par le biais d'une analyse des sentiments, peut permettre d'apporter des améliorations. L'analyse cross-canal est également recommandée pour comprendre l'interaction entre les canaux de marketing et optimiser l'allocation des ressources. Une étude longitudinale permettrait de suivre le comportement des clients au fil du temps, d'anticiper les tendances et de maintenir la pertinence des campagnes. Enfin, l'expérimentation du contenu des catalogues et le développement du marketing numérique permettraient d'accroître l'engagement des différents segments de clientèle.";
        //LEARN
        document.getElementById('learn-h2').textContent = "Apprentissages personnels";
        document.getElementById('learn1').textContent = "Tout au long de mes études, j'ai approfondi divers principes statistiques, tels que l'analyse de régression, la corrélation et les tests d'hypothèse. Cette base m'a permis d'identifier des modèles et des relations dans des ensembles de données, ce qui est particulièrement important dans le domaine du marketing. Par exemple, savoir interpréter la signification des valeurs p et des valeurs R² permet d'évaluer l'efficacité des campagnes de marketing et d'éclairer les processus de prise de décision.";
        document.getElementById('learn2').textContent = "En outre, j'ai appris à appliquer ces concepts statistiques à des scénarios réels, améliorant ainsi ma capacité à développer des modèles prédictifs qui optimisent les stratégies de marketing. Il s'agit notamment de comprendre le comportement des clients, de segmenter les publics et de prédire les taux de réussite des campagnes. En tirant parti des techniques statistiques, je peux analyser des données complexes de manière plus efficace, ce qui permet de prendre des décisions éclairées et d'obtenir de meilleurs résultats en matière de marketing.";
        document.getElementById('learn3').textContent = "Dans l'ensemble, ce parcours d'apprentissage personnel m'a permis d'acquérir les compétences nécessaires pour analyser les données marketing de manière critique, ce qui a permis d'élaborer des stratégies plus efficaces et d'améliorer le retour sur investissement.";
        
    } else if (lang === 'en') {
        //INTRO
        document.getElementById('intro1').textContent = "The marketing landscape is rapidly evolving as businesses compete for consumer attention in an increasingly saturated market.";
        document.getElementById('intro2').textContent = "Traditional methods of campaign planning are no longer enough; marketers need to make informed decisions based on concrete insights about consumer behavior, preferences, and trends.";
        document.getElementById('intro3').textContent = "In this environment, the ability to analyze historical data and predict future outcomes has become a vital competitive advantage. By leveraging data analytics, companies can better allocate resources, personalize their messaging, and optimize the timing and channels of their campaigns.";
        //OBJECTIVE
        document.getElementById('problematic').textContent = "How can we optimize future marketing campaigns to maximize customer engagement by leveraging predictive modeling ?";
        document.getElementById('obj-h2').textContent = "Ojective";
        document.getElementById('obj1').textContent = "The objective was to harness historical data from XYZ Company—including customer profiles, campaign outcomes, and channel performances—to build a model that forecasts the success of future campaigns. This model aims to provide actionable insights for refining marketing strategies and enhancing overall campaign effectiveness.";
        //SOURCE
        document.getElementById('dataset-h2').textContent = "The dataset";
        document.getElementById('source1').textContent = "The data used for this project was sourced from Kaggle, a well-known platform for datasets and data science competitions.";
        document.getElementById('source2').textContent = "The dataset consists of 2,205 observations and includes 39 quantitative variables. Among these variables are key metrics such as age, income, whether the individual responded positively to campaign N, and the amount spent on certain purchases.";
        //SOME INFO
        document.getElementById('someinfo-h2').textContent = "Some key information";
        document.getElementById('info').textContent = "The revenue range among participants varies from €1,730 to €113,734 per year. At least half of the participants have no dependent children. The age of clients ranges from 24 to 80 years, with an average age of approximately 51 years.";
        //PREPARATION
        document.getElementById('dataprep-h2').textContent = "Data preparation for a new model";
        document.getElementById('prep1').textContent = "In our data preparation phase, we construct a model using the total number of campaign acceptances as the response variable. To enhance the accuracy and relevance of our linear regression model, we employ the regsubsets function. This function is instrumental in selecting the most pertinent variables by evaluating all possible subsets of predictors.";
        document.getElementById('prep2').textContent = "By focusing on the most significant variables, we refine our model to better predict the likelihood of campaign success, ensuring a more robust and insightful analysis.";
        document.getElementById('problem1').textContent = "The model we created has linear dependencies between certain variables. The issue arises when several predictive variables are highly correlated, making it difficult for the regression algorithm to distinguish their individual impact on the target variable.";
        // CORRELATION
        document.getElementById('corr1').textContent = "This multicollinearity can lead to unstable coefficient estimates, reducing the model's interpretability. Therefore, we will check for correlations to identify and address any strongly correlated variables before proceeding with model fitting.";
        document.getElementById('corr2').textContent = "Upon examining the provided correlation matrix, several pairs of variables exhibit strong correlations (in absolute value). Notably, Income and MntTotal show a correlation of 0.823, indicating a substantial relationship between a customer's income and their total spending. Similarly, MntWines and MntTotal are highly correlated (corr = 0.9617), as well as MntMeatProducts and MntTotal (corr = 0.9435). Other notable pairs include MntFruits and MntTotal (corr = 0.9288), MntSweetProducts and MntTotal (corr = 0.9079), and MntFishProducts and MntTotal (corr = 0.8875). These strong correlations suggest that total spending is highly influenced by spending across various product categories.";
        document.getElementById('resolcorr1').textContent = "To prevent model errors, we will omit the following variables: MntWines, MntMeatProducts, MntFruits, MntSweetProducts, MntFishProducts, MntRegularProds, AcceptedCmp1, AcceptedCmp2, AcceptedCmp3, AcceptedCmp4, and AcceptedCmp5.";
        document.getElementById('resolcorr2').textContent = "Additionally, certain variables such as Z_CostContact and Z_Revenue do not appear to contribute to the variance of other variables. Moreover, we lack sufficient information about their nature and relevance, which suggests that they could be removed from the dataset.";
        document.getElementById('resolcorr3').textContent = "These variables may introduce multicollinearity or add noise to the model without providing significant predictive power. By excluding them, we aim to improve the model's accuracy and interpretability.";
        //NEW MODEL
        document.getElementById('newmodel-h2').textContent = "A ridge linear model";
        document.getElementById('newmodel1').textContent = "I use the glmnet function to fit regression models, which helps regularize the coefficients in order to better handle issues like multicollinearity. This method reduces the impact of highly correlated variables while retaining all variables in the model, as some of the remaining variables still exhibit strong correlations.";
        document.getElementById('newmoodel2').textContent = "We proceed by fitting the Ridge model using glmnet, and this new model will be referred to as 'best_model'. The next step is to display the coefficients of each variable, which is crucial for interpreting the model and understanding the relative importance of each explanatory variable.";
        document.getElementById('newmodel3').textContent = "In our case, for a linear regression, each coefficient will indicate how much the target variable changes on average for a one-unit change in the explanatory variable, holding all other factors constant. This means that each coefficient represents the isolated effect of the corresponding variable on the target, providing insight into the relationship between the predictors and the outcome of interest.";
        document.getElementById('newmodel4').textContent = "In the model, variables with non-zero coefficients are considered to have an impact on the target variable. A positive coefficient indicates that an increase in the explanatory variable leads to an increase in the target variable. Conversely, a negative coefficient implies that an increase in the explanatory variable results in a decrease in the target variable. Variables with zero coefficients can be ignored in the interpretation, as they do not significantly influence the outcome.";
        document.getElementById('newmodel5').textContent = "We created a linear model (using the lm function) and then generated a summary of the results. The R² value is 0.431, indicating that the model explains approximately 43.1% of the total variance in the dependent variable. This suggests that the model captures a significant portion of the observed variability. The F-test evaluates the overall significance of the model.";
        document.getElementById('newmodel6').textContent = "With an F-statistic of 66.01 and a p-value close to zero (p-value : 2.2e-16), this implies that the model as a whole is statistically significant. In other words, at least one of the independent variables has a significant effect on the dependent variable. The analysis also reveals notable trends: for each additional teenager in the household, there is a 0.059 decrease in the likelihood of accepting the marketing campaign.";
        document.getElementById('newmodel7').textContent = " In our model, we found that each promotional purchase is linked to a decrease of 0.0366 in the acceptance rate, while each in-store purchase results in a reduction of 0.02528. Conversely, customers who accepted the most recent campaign show a significant increase of 0.6566 in the dependent variable. Regarding education, levels such as Second Cycle, Basic, and Graduation are associated with higher response rates, highlighting the significant influence of education on attitudes related to the dependent variable.";
        //TEST
        document.getElementById('test-h2').textContent = "Statistical test to data";
        document.getElementById('test1').textContent = " We will conduct normality (Shapiro-Wilk), heteroscedasticity (Breusch-Pagan), and residual autocorrelation (Durbin-Watson) tests, with a significance threshold of 0.05 for each";
        document.getElementById('test2').textContent = "The Shapiro-Wilk test checks whether the residuals of a regression model follow a normal distribution. The normality of residuals is crucial for certain regression models, particularly for the validity of significance tests (p-values) and confidence intervals.";
        document.getElementById('test3').textContent = "The homoscedasticity assumption (constant variance of errors) is a key condition in classical linear regression. If this assumption is violated (i.e., heteroscedasticity is present), the standard errors of the estimated coefficients may be inaccurate, affecting the reliability of p-values and confidence intervals. A model with heteroscedasticity can produce less reliable predictions and underestimate the variability of the estimates.";
        document.getElementById('test4').textContent = "The Durbin-Watson test checks for autocorrelation of residuals, meaning whether the errors (residuals) of a model are correlated with each other. If residuals are correlated, it indicates that the model has not captured all the structure in the data. Autocorrelation can result in inefficient coefficient estimates, which impacts the model's predictive power.";
        document.getElementById('test5').textContent = "For a 5% threshold, we observe that these three tests are passed.";
        //CHART
        document.getElementById('chart-h2').textContent = "Charts and Key Insights";
        document.getElementById('chart1').textContent = "Without a doubt, the vast majority of customers did not respond positively to any of the advertising campaigns we conducted. We should focus on identifying the key criteria related to our customers behavior patterns. By doing so, we can better allocate our marketing investments, ensuring that they are targeted and more likely to yield positive results.";
        document.getElementById('chart2').textContent = "We can observe that nearly all customers shop in-store, yet many do not use the catalog. This presents an opportunity to improve either by revising the catalog content or increasing its distribution to a broader audience. Additionally, the store's website plays a significant role in driving purchases. We could consider investing more in digital marketing to attract more  customers, especially in today's increasingly digital era.";
        document.getElementById('chart3').innerHTML = "We can observe that the vast majority of customers shop in-store, although many do not use the catalog. This presents an opportunity for improvement by either revising the catalog content or distributing it to a wider audience. <br> Additionally, the store's website plays a significant role in driving purchases. We could focus on increasing digital marketing efforts to attract more customers, especially considering our current era, which is becoming increasingly digital.";
        //AGE CORRELATION
        document.getElementById('agecorr-h2').textContent = "Age and correlation";
        document.getElementById('agecorr').innerHTML = "We observe that most customers are between 30 and 70 years old, which can be identified as adults, parents, or even grandparents. <br> The graph shows the correlation between customer age and the number of accepted advertising campaigns (`AcceptedCmpOverall`). Each point represents a customer, with age on the x-axis and the number of accepted campaigns on the y-axis. <br> It appears that campaign acceptance is not strongly influenced by age. The acceptance values are spread across all age groups without a clear trend. This suggests that there is no obvious relationship between age and the likelihood of accepting advertising campaigns, indicating that a marketing strategy targeting based solely on age would not be optimal. Instead, it would be better to design campaigns that appeal to a broad audience to maximize reach.";
        //INTERPRETATION
        document.getElementById('interp-h2').textContent = "Interpretation";
        document.getElementById('interp1').textContent = "In conclusion, our analysis reveals important insights into customer behavior and the effectiveness of marketing campaigns. Although we initially hypothesized that factors like age might play a crucial role in campaign acceptance, the data shows otherwise. The correlation analysis suggests no clear relationship between age and campaign acceptance, indicating that targeted age-specific marketing may not be effective.";
        document.getElementById('interp2').textContent = "Instead, our findings highlight the importance of a broad, inclusive marketing approach. The correlation between income and total spending suggests that customers with higher incomes tend to spend more across all categories, emphasizing the need for targeted offers based on purchasing power rather than demographic characteristics such as age.";
        document.getElementById('interp3').textContent = "Moreover, the variable selection process and Ridge regression model helped refine the predictive power by focusing on the most impactful factors, thereby improving the model’s robustness and interpretability. The statistical tests indicate that our model meets the assumptions necessary for reliable analysis, providing confidence in the results.";
        document.getElementById('interp4').textContent = "In terms of actionable strategies, improving catalog usage and investing in digital marketing channels appear to be promising areas. The store's website has proven to be a significant driver of purchases, suggesting that enhancing our digital marketing efforts could attract more customers, particularly in today's digital landscape. " ;
        document.getElementById('interp5').textContent = "Ultimately, our goal should be to identify the key behavioral criteria that can guide marketing investment, ensuring that campaigns are both efficient and effective, maximizing response rates and improving return on investment.";
        //RECOMMENDATION
        document.getElementById('recom-h2').textContent = "Recommendation";
        document.getElementById('recomtext').textContent = "First, a detailed customer segmentation analysis should be conducted to design more targeted campaigns for different groups. Additionally, further behavioral analysis could help identify motivations behind purchasing decisions, providing more refined targeting criteria. A/B testing of different campaign versions would allow us to determine the most effective approaches, while incorporating additional data sources, such as social media engagement or geographic data, could improve predictive accuracy. Analyzing customer feedback, such as reviews or survey responses, through sentiment analysis can guide improvements. Cross-channel analysis is also recommended to understand the interaction between marketing channels and optimize resource allocation. A longitudinal study would help track customer behavior over time, anticipating trends and maintaining campaign relevance. Finally, experimenting with catalog content and expanding digital marketing would help increase engagement across different customer segments.";
        //LEARN
        document.getElementById('learn-h2').textContent = "Personal Learnings";
        document.getElementById('learn1').textContent = "Through my studies, I have delved into various statistical principles, such as regression analysis, correlation, and hypothesis testing. This foundation has enabled me to identify patterns and relationships within data sets, which is particularly important in marketing. For instance, knowing how to interpret the significance of p-values and R² values helps assess the effectiveness of marketing campaigns and informs decision-making processes.";
        document.getElementById('learn2').textContent = "Additionally, I have learned to apply these statistical concepts in real-world scenarios, enhancing my ability to develop predictive models that optimize marketing strategies. This includes understanding customer behavior, segmenting audiences, and predicting campaign success rates. By leveraging statistical techniques, I can analyze complex data more effectively, allowing for informed decisions that drive better marketing outcomes.";
        document.getElementById('learn3').textContent = "Overall, this personal learning journey has equipped me with the necessary skills to analyze marketing data critically, leading to more effective strategies and improved return on investment."
    }
}